Rcm: rcup now creates symlink ~/.dotfiles
using the variable DOTFILES_DIR defined in rcc.
    ln -s "$DOTFILES_DIR" ~/.dotfiles

diff --git a/hooks/pre-up b/hooks/pre-up
--- a/hooks/pre-up
+++ b/hooks/pre-up
@@ -4,4 +4,17 @@
 # This hook is run everytime rcup is run
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-ln -s ~/dev/dotfiles/ ~/.dotfiles
+# Create ~/.dotfiles
+if [ -e ~/.dotfiles ] ; then
+	echo "WARNING: ~/.dotfiles already exists" >&2
+	ls -l ~/.dotfiles
+	exit 1
+fi
+
+if ! ln -s "$DOTFILES_DIRS" ~/.dotfiles ; then
+	echo "WARNING: Cannot create ~/.dotfiles" >&2 
+	exit 2
+fi
+
+echo "Created ~/.dotfiles => ($DOTFILES_DIRS)"
+exit 0
